### ISSUE TITLE
Error on import due to missing dependencies - ModuleNotFoundError: No module named 'jsonpatch'

### ISSUE THREAD

**Issue by tauhlim** [supervisely/supervisely#101]
I just tried a fresh install on python 3.8 following the instructions here: https://sdk.docs.supervise.ly/rst_templates/installation/installation/installation.html

When trying to `import supervisely`:

```
>>> import supervisely
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda3/envs/supervisely/lib/python3.8/site-packages/supervisely/__init__.py", line 100, in <module>
    import supervisely.app as app
  File "/opt/miniconda3/envs/supervisely/lib/python3.8/site-packages/supervisely/app/__init__.py", line 1, in <module>
    from supervisely.app.content import StateJson, DataJson, LastStateJson, ContextJson
  File "/opt/miniconda3/envs/supervisely/lib/python3.8/site-packages/supervisely/app/content.py", line 5, in <module>
    import jsonpatch
ModuleNotFoundError: No module named 'jsonpatch'
```

**Comment by tauhlim** [comment]
As an update, if I use `pip install 'supervisely[apps]'`, it works.

However I believe this is still a valid issue as `import supervisely` should work without specifying any extras during installation.

**Comment by qanelph** [comment]
@tauhlim fixed in https://github.com/supervisely/supervisely/commit/396e09375ad2040313865ddace973407d4e7b940
