### ISSUE TITLE
download_project doesn't work with log_progress=True

### ISSUE THREAD

**Issue by Jihadik** [supervisely/supervisely#12]
I'm trying to download my project with `log_progress=True` and here what it outputs:
```
<class 'pythonjsonlogger.jsonlogger.JsonEncoder'>
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.7/logging/__init__.py", line 1034, in emit
    msg = self.format(record)
  File "/usr/lib/python3.7/logging/__init__.py", line 880, in format
    return fmt.format(record)
  File "/home/ubuntu/.virtualenvs/supervisely/lib/python3.7/site-packages/pythonjsonlogger/jsonlogger.py", line 209, in format
    return "%s%s" % (self.prefix, self.jsonify_log_record(log_record))
  File "/home/ubuntu/.virtualenvs/supervisely/lib/python3.7/site-packages/pythonjsonlogger/jsonlogger.py", line 172, in jsonify_log_record
    ensure_ascii=self.json_ensure_ascii)
  File "/home/ubuntu/celly/3rd_party/supervisely/supervisely_lib/sly_logger.py", line 109, in dumps_ignore_nan
    return simplejson.dumps(obj, ignore_nan=True, *args, **kwargs)
  File "/home/ubuntu/.virtualenvs/supervisely/lib/python3.7/site-packages/simplejson/__init__.py", line 400, in dumps
    **kw).encode(obj)
TypeError: __init__() got an unexpected keyword argument 'encoding'
Call stack:
  File "run.py", line 26, in <module>
    download_project(api, 27614, "./test", log_progress=True)
  File "/home/ubuntu/celly/3rd_party/supervisely/supervisely_lib/project/project.py", line 342, in download_project
    'Downloading dataset: {!r}'.format(dataset_info.name), total_cnt=len(images))
  File "/home/ubuntu/celly/3rd_party/supervisely/supervisely_lib/task/progress.py", line 21, in __init__
    self.report_progress()
  File "/home/ubuntu/celly/3rd_party/supervisely/supervisely_lib/task/progress.py", line 35, in report_progress
    'total': math.ceil(self.total),
  File "/home/ubuntu/celly/3rd_party/supervisely/supervisely_lib/sly_logger.py", line 75, in <lambda>
    **kwargs)
Message: 'progress'
Arguments: ()
```

I tried to dig it in a bit and it's not clear, why the exception happens. Here is the output of my `pip freeze` in case you are unable to reproduce it:
```
aniso8601==6.0.0
certifi==2019.3.9
chardet==3.0.4
Click==7.0
cycler==0.10.0
decorator==4.4.0
Flask==1.0.3
Flask-RESTful==0.3.7
grpcio==1.21.1
idna==2.8
imageio==2.5.0
itsdangerous==1.1.0
Jinja2==2.10.1
jsonschema==2.6.0
kiwisolver==1.1.0
MarkupSafe==1.1.1
matplotlib==2.2.4
networkx==2.3
numpy==1.16.4
opencv-python==3.4.5.20
pascal-voc-writer==0.1.4
Pillow==5.4.1
protobuf==3.8.0
PTable==0.9.2
pyparsing==2.4.0
python-dateutil==2.8.0
python-json-logger==0.1.11
pytz==2019.1
PyWavelets==1.0.3
requests==2.22.0
requests-toolbelt==0.9.1
scikit-image==0.15.0
scipy==1.3.0
Shapely==1.6.4.post2
simplejson==3.16.0
six==1.12.0
-e git+https://github.com/supervisely/supervisely.git@21451073c44fa844446f397433bdce96634a8010#egg=supervisely
urllib3==1.25.3
Werkzeug==0.15.4
```

**Comment by antonc-ds** [comment]
Yup, can reproduce. Need to figure out what we do differently in our containers so that is works..

**Comment by antonc-ds** [comment]
Found it. We are using older python-json-logger in our docker images (0.1.8 vs 0.1.11 in the pip config). Apparently something changed there to break compatibility with simplejson. I am going to downgrade python-json-logger version in setup.py as a quick fix for now and make a note to investigate in more detail later. Thanks for reporting this!

**Comment by antonc-ds** [comment]
Fixed in https://github.com/supervisely/supervisely/pull/14
