### ISSUE TITLE
supervisely throughing error while training

### ISSUE THREAD

**Issue by veenadivya** [supervisely/supervisely#37]
Fatal

2020.08.27 20:57:42

Unexpected exception in main.

main_name=YOLO_V3_TRAIN, stack=[
  Traceback (most recent call last):
    File "/workdir/supervisely_lib/function_wrapper.py", line 14, in main_wrapper
      main_func(*args, **kwargs)
    File "/workdir/src/train.py", line 301, in main
      x = YOLOTrainer()
    File "/workdir/src/train.py", line 84, in __init__
      super().__init__(default_config=YOLOTrainer.get_default_config())
    File "/workdir/supervisely_lib/nn/hosted/trainer.py", line 85, in __init__
      self._construct_and_fill_model()
    File "/workdir/src/train.py", line 102, in _construct_and_fill_model
      self._make_yolo_train_config()
    File "/workdir/src/train.py", line 180, in _make_yolo_train_config
      yolo_config = read_config(os.path.join(sly.TaskPaths.MODEL_DIR, MODEL_CFG))
    File "/workdir/src/yolo_config_utils.py", line 18, in read_config
      with open(file_path, 'r') as fin:
  FileNotFoundError: [Errno 2] No such file or directory: '/sly_task_data/model/model.cfg'
]

Fatal

2020.08.27 20:57:47

TASK_END

stack=[
  Traceback (most recent call last):
    File "/workdir/src/worker/task_logged.py", line 128, in run
      self.run_and_wait(self.task_main_func)
    File "/workdir/src/worker/task_logged.py", line 157, in run_and_wait
      return future.result()
    File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 425, in result
      return self.__get_result()
    File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
      raise self._exception
    File "/usr/local/lib/python3.6/concurrent/futures/thread.py", line 56, in run
      result = self.fn(*self.args, **self.kwargs)
    File "/workdir/src/worker/task_dockerized.py", line 80, in task_main_func

      curr_method()
    File "/workdir/src/worker/task_dockerized.py", line 109, in main_step
      self.drop_container_and_check_status()
    File "/workdir/src/worker/task_dockerized.py", line 256, in drop_container_and_check_status
      raise RuntimeError('Task container finished with non-zero status: {}'.format(str(status)))
  RuntimeError: Task container finished with non-zero status: {'Error': None, 'StatusCode': 1}
]

need help with this error, as i am new to this API[](url)

**Comment by manpreet-tatras** [comment]
You need to create sly_task_data/model and put model.cfg and pretrained weights you will be using inside that model folder.
your directory structure should be something like:-
/-- sly_task_data/
    |-- data/
    |   |-- training-project-name/
    |-- model/
    |   |-- config.json
    |   |-- model_specific_initial_weights
    |-- results/
    |-- task_config.json
I got this from https://github.com/supervisely/supervisely/blob/master/help/tutorials/03_custom_neural_net_plugin/custom_nn_plugin.md

**Comment by manpreet-tatras** [comment]
**data** contains the training data as a Supervisely project. We strongly suggest using our Python SDK (starting from supervisely_lib.project.project module)to read, parse and transform the data instead ofworking with raw JSON files.

For now, training only runs with one input project, but support for multiple projects may be added in the future.

**model directory** contains two components:

model_specific_initial_weights us a checkpoint, in whatever format your model supports, with pretrained weights that are used to initialize the model for training. The name can be anything, this is all determined by your plugin code. For example, for PyTorch models we usually use model.pt as a weights checkpoint file, while for TensorFlow we usually use a 'model_weights' directory with several files comprising a TensorFlow checkpoint.

It is possible, but rather not typical, to not have this file/directory. If your model supports weights initialization completely from scratch, see later in this guide how to set up training without this file.

**config.json** describes the model configuration corresponing to the initial weights checkpoint above. It is a json dict with 3 sections like this:

{
  "settings": {
    # Model-specific settings, e.g. num_convolution_layers, enable_batchnorm etc
  },
  "out_classes": [
    # A list of output Supervisely object classes for the checkpointted model.
    {"title": "bg", "shape": "bitmap", "color": "#BAFA92"},
    {"title": "kiwi", "shape": "bitmap", "color": "#FF0000"},
    {"title": "lemon", "shape": "bitmap", "color": "#51C6AA"}
  ],
  "class_title_to_idx": {
    # Correspondence between the Supervisely classes above and the integer class
    # IDs of the model.
    # This is used when continuing training from an existing checkpoint for the
    # same set of classes to make sure the newly built class apping is
    # consistent with the checkpoint.
    "bg": 0,
    "kiwi": 1,
    "lemon": 2
  }
}
**results** is the directory to which the intermediate training checkpoints and final results should be written by the code in train.py.

**task_config.json** is a JSON config, filled in by the user in the web UI before kicking off the training. Although in principle the structure here may be arbitrary, depending on how you decide to handle configuration, we have worked out a common structure for our own plugins and suggest keeping to that structure. In particular, this will make it possible to rely on the training helpers in the SDK (supervisely_lib.nn.hosted.trainer)

{
  "lr": 0.001,  # Add other model and optimizer settings here.

  "epochs": 3,  # The number of passes over the whole training data.

  # How frequently to validate on the validation fold. 0.5 means every half
  # an epoch.
  "val_every": 0.5,

  # Batch sizes to use for training and validation.
  "batch_size": {
    "val": 3,
    "train": 3
  },

  # We use tags to split the input project into train and validation folds.
  # Here the values of the map are the tag names to use for the two folds.
  # All the images where a given tag is present will be assigned to its
  # respective fold.
  "dataset_tags": {
    "val": "val",
    "train": "train"
  },

  # Here wew are using two possible values:
  # - "continue_training": continue training on a dataset fully compatible
  #   with the predicted classes of the initial checkpoint.
  # - "transfer_learning": reset the head (last layer(s) of the model) to
  #   match the classes of the training dataset. This may involve changing
  #   the dimensions of the head to match the new number of predicted
  #   classes and should always involve resetting head  randomly.
  "weights_init_type": "transfer_learning"  # or "continue_training"
}
